### ISSUE TITLE
Site is not responding from gateway

### ISSUE THREAD

**Issue by ghv** [porter-io/feedback#11]

**Comment by ghv** [comment]
Closing this issue as the site is working now.

**Comment by ghv** [comment]
https://porter.io and digests are down again. It's been like this for a while.

**Comment by jlsync** [comment]
yes, https://porter.io and digests are down for a while now. I really enjoy my daily digest when it's working!

**Comment by ghv** [comment]
It's back up. I also email hi@porter.io -- seems to get more attention that way.

**Comment by ghv** [comment]
Dang, that did not last long. I noticed this was back down since since 7/4.

**Comment by ghv** [comment]
Still down 😞.

**Comment by jlsync** [comment]
Hi @ledzep2 @adieu @sebibleci ,

 https://porter.io and digest links are still down. Any chance of looking at this problem? Really miss my digests!

A possible workaround is to make the daily email longer - allowing for more links to be included or even the full digest?

**Comment by ghv** [comment]
The website is back! 🤞it stays that way!  Thank you!

**Comment by ghv** [comment]
Porter digest site is down again since Feb. 19th.

**Comment by DennisSuitters** [comment]
Still not opening, maybe they need to consider better hosting.

**Comment by ghv** [comment]
I just noticed this was back up as of today.

**Comment by ghv** [comment]
My thanks to Porter.io folks for getting this resolved! Closing this for now.

**Comment by ghv** [comment]
It has been back down again since Friday the 13th.  The last time it was down, it took 30 days to repair.

**Comment by ghv** [comment]
I meant to close this a while back. This has been back since over a few weeks ago.
