### ISSUE TITLE
Use of porter 

### ISSUE THREAD

**Issue by vid** [porter-io/feedback#2]
I thought porter was about helping me organize and stay on top of the many repos I'm already Iintentionally subscribed to. That would be very useful to me. Another set of guesses at what I'm interested in is the opposite.  Thanks.

**Comment by ledzep2** [comment]
Sorry for the super late response. I'm not really sure what meant. Since this is a very old issue, I'm gonna close it. Please re-open if you wanna continue the discussion. Thank you very much.
