### ISSUE TITLE
delete my account please

### ISSUE THREAD

**Issue by lookfirst** [porter-io/feedback#3]
i tried to turn off all the email notifications, but i'm still getting them. please delete my account from your system. =)

**Comment by sebie** [comment]
Same as above, please delete my account.

**Comment by lgaticaq** [comment]
Please delete my account

**Comment by ledzep2** [comment]
Sorry for the super late response. Unsubscribe was fixed some time ago. And now Porter has an news reader app which doesn't push anything. If you still wish to delete your accounts, please leave a comment soon. I plan to clean up dated issues within this week. Thank you very much.

**Comment by lookfirst** [comment]
I already left a comment... on May 11, 2015.

**Comment by ledzep2** [comment]
> I already left a comment... on May 11, 2015.

Terribly sorry about that. Your account is deleted. Thanks for the feedback.

**Comment by sebie** [comment]
> Sorry for the super late response. Unsubscribe was fixed some time ago. And now Porter has an news reader app which doesn't push anything. If you still wish to delete your accounts, please leave a comment soon. I plan to clean up dated issues within this week. Thank you very much.

Please delete the account.

**Comment by ledzep2** [comment]
@sebie Deleted. Sorry again for the delay. 

I'm closing this issue for now. Please re-open if you need further assistance.
