### ISSUE TITLE
Hacker News links

### ISSUE THREAD

**Issue by lleaff** [porter-io/feedback#4]
It'd be nice if links to the Hacker News (or whatever other platform the story is taken from) comment feed was displayed alongside the main links.

**Comment by ledzep2** [comment]
Sorry for the super late response. We were caught up in something else. 

Porter has an app now which allows you to open article link, Hacker News link and related Github repo links. Hopefully that will be useful to you. Links are on https://porter.io. Thanks for the feedback. I'm closing this issue for now. Please re-open if you have further suggestions.
