### ISSUE TITLE
Cannot change email address

### ISSUE THREAD

**Issue by jnv** [porter-io/feedback#6]
I would like to receive weekly digests to a different e-mail address associated with my GitHub profile. When I go to Me / Preference / Common, I set a different e-mail and hit save, however upon page refresh the original e-mail is still selected and I still receive digests to a different address. It looks like my preference is not saved on the server at all. What is wrong?

**Comment by GETandSELECT** [comment]
+1 same issue here

**Comment by ledzep2** [comment]
Fixed. Sorry for the super late response. We were caught up in something else. Good news is, Porter has an app now. Links are on https://porter.io. Please have a try. Thanks for the feedback. I'm closing this issue for now.
