### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by lookfirst** [porter-io/feedback#7]
I never requested a daily 'Repo Update:' email, yet I'm getting one now.

In order to unsubscribe, I have to authorize your app on github.

No offense, but that's just wrong.

**Comment by ledzep2** [comment]
Sorry for any trouble it caused you. I've already deactivated your subscription. 

Now just for debugging, can you tell me if you had logged in with your github id and completed the subscription wizard, then revoked the authorization? It will help us improve. Thank you.

**Comment by lookfirst** [comment]
@ledzep2 I can't remember, sorry!
